"""
Data structures for student availability and recommendations.

Utilizes Python's dataclasses to create lightweight, structured data transfer objects (DTOs).
This ensures strict type hinting and a predictable memory footprint when the scheduling 
algorithm needs to iterate over large arrays of time blocks to calculate overlaps.
"""
from dataclasses import dataclass


@dataclass
class ScheduleBlock:
    """
    Represents a hard constraint within the scheduling search space.
    
    During the evaluation phase, instances of ScheduleBlock act as invalid bounding boxes. 
    The algorithm maps these against candidate office hour slots; any collision results 
    in a penalty or a boolean rejection for that specific time window.
    """
    participant_name: str
    participant_email: str
    day: str
    start_time: str
    end_time: str
    block_type: str  # e.g. "Class", "Work", "Other"


@dataclass
class Recommendation:
    """
    Represents a candidate solution generated by the scheduling algorithm.
    
    The 'score' attribute holds the result of the algorithm's fitness/objective function. 
    It quantifies the optimality of the time window based on cohort availability, 
    allowing the backend to sort the array of Recommendations and return the top 'k' slots.
    """
    start_time: str
    end_time: str
    score: float
